apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  labels:
    app: node-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
      - name: sit323-2025-prac2p
        image: zeyulinn/sit323_5.1p:latest
        ports:
        - containerPort: 3000
