apiVersion: v1
kind: Service
metadata:
  name: node-web-service
spec:
  type: NodePort
  selector:
    app: node-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001